permalink:           pretty

# Setup
title:               'Health Informatics (Elective)'
url:                 https://prabinrs.github.io/HI2023/
baseurl:             '/HI2023'
homepage_title:      Home
default_lang:        'en'

# About/contact
author:
name:                prabin
url:                 https://twitter.com/prabincha
github:
  repo:              https://github.com/prabinrs/HI2023

# Custom vars
version:             hi2023

src:                 "."
default_theme:       "ayu"

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "custom"

# For Maths
markdown:            kramdown

# To use hljs, disable the default highlighter
kramdown:
  syntax_highlighter_opts:
    disable: true
  math_engine: null

exclude:
  - jekyllbook
  - en/index.md
  - vendor


################################### English ####################################
prologues:
  - path: en/faq.md
Modules:
  - path: en/week01/01.md
  - path: en/week02/02.md
    sections:
        - path: en/week02/02-3.md
  - path: en/week03/03.md
    sections:
        - path: en/week03/03-3.md
  - path: en/week04/04.md
  - path: en/week05/05.md
  - path: en/week06/06.md
  - path: en/week07/07.md
    sections:
      - path: en/week07/07-3.md
  - path: en/week08/08.md
    sections:
      - path: en/week08/08-3.md
  - path: en/week09/09.md
    sections:
        - path: en/week09/09-3.md
  - path: en/week10/10.md
    sections:
        - path: en/week10/10-1.md
        - path: en/week10/10-2.md
        - path: en/week10/10-3.md
  - path: en/week11/11.md
    sections:
        - path: en/week11/11-1.md
        - path: en/week11/11-2.md
  - path: en/week12/12.md
    sections:
        - path: en/week12/12-1.md
        - path: en/week12/12-2.md
        - path: en/week12/12-3.md
  - path: en/week13/13.md
  - path: en/week14/14.md
  - path: en/week15/15.md
    sections:
        - path: en/week15/15-1.md
        - path: en/week15/15-2.md        
