permalink:           pretty

# Setup
title:               'Health Informatics (Elective)'
url:                 https://prabinrs.github.io/HI2023/
baseurl:             'HI2023/docs'
homepage_title:      Home
default_lang:        'en'

# About/contact
author:
name:                prabin
url:                 https://twitter.com/prabincha
github:
  repo:              https://github.com/prabinrs/HI2023

# Custom vars
version:             1.0.0

src:                 "."
default_theme:       "ayu"

# For Maths
markdown:            kramdown

# To use hljs, disable the default highlighter
kramdown:
  syntax_highlighter_opts:
    disable: true
  math_engine: null

exclude:
  - jekyllbook
  - vendor


################################### English ####################################
prologues:
  - path: en/faq.md
chapters:
  - path: en/week01/01.md
    sections:
      - path: en/week01/01_01.md
      - path: en/week01/01_02.md
      - path: en/week01/01_02.md
  - path: en/week02/02.md
  - path: en/week03/03.md
    sections:
        - path: en/week03/03_0.md  
